service: aws-lambda-ssm-access
frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  memorySize: 256
  runtime: nodejs18.x
  environment:
    AWS_REGION_NAME: ${param:AWS_REGION_NAME}
    AWS_PARAMETER_STORE_NAME: ${param:AWS_PARAMETER_STORE_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameterHistory
            - ssm:GetParametersByPath
            - ssm:GetParameters
            - ssm:GetParameter
          Resource: arn:aws:ssm:*:${param:AWS_ACCOUNT_ID}:parameter${param:AWS_PARAMETER_STORE_NAME}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3333

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
